//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camion()
        {
            this.ChangeLogCamions = new HashSet<ChangeLogCamion>();
            this.ChangeLogChofers = new HashSet<ChangeLogChofer>();
            this.Rutas = new HashSet<Ruta>();
        }
    
        public int Id { get; set; }
        public int Tipo { get; set; }
        public string Matricula { get; set; }
        public int Modelo { get; set; }
        public string Marca { get; set; }
        public bool Disponibilidad { get; set; }
        public double Kilometraje { get; set; }
        public string UrlFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeLogCamion> ChangeLogCamions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeLogChofer> ChangeLogChofers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruta> Rutas { get; set; }
    }
}
