//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLogChofer
    {
        public int Id { get; set; }
        public string Actionn { get; set; }
        public Nullable<int> IdChofer { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
    
        public virtual Camion Camion { get; set; }
    }
}
