//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class companyEntities : DbContext
    {
        public companyEntities()
            : base("name=companyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camion> Camions { get; set; }
        public virtual DbSet<ChangeLogCamion> ChangeLogCamions { get; set; }
        public virtual DbSet<ChangeLogChofer> ChangeLogChofers { get; set; }
        public virtual DbSet<ChangeLogRuta> ChangeLogRutas { get; set; }
        public virtual DbSet<Chofer> Chofers { get; set; }
        public virtual DbSet<Ruta> Rutas { get; set; }
        public virtual DbSet<ViewCamion> ViewCamions { get; set; }
        public virtual DbSet<ViewChofer> ViewChofers { get; set; }
        public virtual DbSet<ViewRuta> ViewRutas { get; set; }
    
        public virtual int SP_Delete_Camion(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Camion", idCamionParameter);
        }
    
        public virtual int SP_Delete_chofer(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_chofer", idChoferParameter);
        }
    
        public virtual int SP_Delete_Ruta(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Ruta", idRutaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_insert_camion(Nullable<int> tipo, string matricula, Nullable<int> modelo, string marca, Nullable<bool> disponibilidad, Nullable<double> kilometraje, string urlFoto)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_insert_camion", tipoParameter, matriculaParameter, modeloParameter, marcaParameter, disponibilidadParameter, kilometrajeParameter, urlFotoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_Insert_chofer(string nombre, string apellidoPaterno, string apellidoMaterno, string licencia, string telefono, Nullable<bool> disponibilidad)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_Insert_chofer", nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, licenciaParameter, telefonoParameter, disponibilidadParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_insert_ruta(string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<System.DateTime> fechaRegistro, Nullable<bool> aTiempo, Nullable<double> distancia, Nullable<int> idCamion, Nullable<int> idChofer)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_insert_ruta", origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, fechaRegistroParameter, aTiempoParameter, distanciaParameter, idCamionParameter, idChoferParameter);
        }
    
        public virtual int SP_update_camion(Nullable<int> idCamion, Nullable<bool> nuevaDisponibilidad)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("idCamion", idCamion) :
                new ObjectParameter("idCamion", typeof(int));
    
            var nuevaDisponibilidadParameter = nuevaDisponibilidad.HasValue ?
                new ObjectParameter("NuevaDisponibilidad", nuevaDisponibilidad) :
                new ObjectParameter("NuevaDisponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_update_camion", idCamionParameter, nuevaDisponibilidadParameter);
        }
    
        public virtual int SP_Update_Chofer(Nullable<int> idChofer, Nullable<bool> nuevaDisponibilidad)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var nuevaDisponibilidadParameter = nuevaDisponibilidad.HasValue ?
                new ObjectParameter("NuevaDisponibilidad", nuevaDisponibilidad) :
                new ObjectParameter("NuevaDisponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Chofer", idChoferParameter, nuevaDisponibilidadParameter);
        }
    
        public virtual int SP_Update_Ruta(Nullable<int> idRuta, Nullable<System.DateTime> nuevaFechaSalida, Nullable<System.DateTime> nuevaFechaLlegada)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            var nuevaFechaSalidaParameter = nuevaFechaSalida.HasValue ?
                new ObjectParameter("NuevaFechaSalida", nuevaFechaSalida) :
                new ObjectParameter("NuevaFechaSalida", typeof(System.DateTime));
    
            var nuevaFechaLlegadaParameter = nuevaFechaLlegada.HasValue ?
                new ObjectParameter("NuevaFechaLlegada", nuevaFechaLlegada) :
                new ObjectParameter("NuevaFechaLlegada", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Ruta", idRutaParameter, nuevaFechaSalidaParameter, nuevaFechaLlegadaParameter);
        }
    }
}
