//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.ChangeLogRutas = new HashSet<ChangeLogRuta>();
        }
    
        public int Id { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool ATiempo { get; set; }
        public double Distancia { get; set; }
        public Nullable<int> IdCamion { get; set; }
        public Nullable<int> IdChofer { get; set; }
    
        public virtual Camion Camion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeLogRuta> ChangeLogRutas { get; set; }
        public virtual Chofer Chofer { get; set; }
    }
}
