//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRuta
    {
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<int> IdCamion { get; set; }
        public Nullable<int> IdChofer { get; set; }
    }
}
