//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fotografiaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photographers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photographers()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Materno { get; set; }
        public string Paterno { get; set; }
        public string Username { get; set; }
        public string UrlFoto { get; set; }
        public string Password { get; set; }
        public string Instagram { get; set; }
        public string Facebook { get; set; }
        public string Email { get; set; }
        public string Biography { get; set; }
        public int Type_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual TypeUsers TypeUsers { get; set; }
    }
}
