use photography;

CREATE TABLE TypeUsers(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Type VARCHAR(100) NOT NULL
)

CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Photographers(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Materno VARCHAR(100) NOT NULL,
	Paterno VARCHAR(100) NOT NULL,
	Username VARCHAR(100) NOT NULL,
	UrlFoto VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Instagram VARCHAR(200) NOT NULL,
	Facebook VARCHAR(200) NOT NULL,
	Email VARCHAR(200) NOT NULL,
	Biography VARCHAR(200) NOT NULL,
	Type_User INT NOT NULL,
	CONSTRAINT fk_Users_TypeUsers FOREIGN KEY(Type_User)
		REFERENCES TypeUsers(Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
);

CREATE TABLE Photos(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR(100) NOT NULL,
	Description VARCHAR(200),
	Created_date DATETIME NOT NULL,
	Photographer_Id INT NOT NULL,
	Category_Id INT NOT NULL,
	CONSTRAINT fk_Photo_Category FOREIGN KEY(Category_Id)
		REFERENCES Categories(Id)
		ON DELETE NO ACTION 
		ON UPDATE NO ACTION,
	CONSTRAINT fk_Photo_Photographer FOREIGN KEY(Photographer_Id)
		REFERENCES Photographers(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

);