use photography;

CREATE TABLE TypeUsers(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Type VARCHAR(100) NOT NULL
)

CREATE TABLE Categories(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Places(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Country VARCHAR(100) NOT NULL,
	State VARCHAR(100),
	Name VARCHAR(150)
)

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Materno VARCHAR(100) NOT NULL,
	Paterno VARCHAR(100),
	Username VARCHAR(100) NOT NULL,
	Password VARCHAR(100) NOT NULL,
	Instagram VARCHAR(200) NOT NULL,
	Facebook VARCHAR(200) NOT NULL,
	Type_User INT NOT NULL,
	CONSTRAINT fk_Users_TypeUsers FOREIGN KEY(Type_User)
		REFERENCES TypeUsers(Id)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
);

CREATE TABLE Photos(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR(100) NOT NULL,
	Url_Photo VARCHAR(200) NOT NULL,
	Created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	User_Id INT NOT NULL,
	Category_Id INT NOT NULL,
	Place_Id INT,
	CONSTRAINT fk_Photo_Category FOREIGN KEY(Category_Id)
		REFERENCES Categories(Id)
		ON DELETE NO ACTION 
		ON UPDATE NO ACTION,
	CONSTRAINT fk_Photo_Place FOREIGN KEY(Place_Id)
		REFERENCES Places(Id)
		ON DELETE NO ACTION 
		ON UPDATE NO ACTION,
	CONSTRAINT fk_Photo_User FOREIGN KEY(User_Id)
		REFERENCES Users(Id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

);