-- UPDATE CAMION
BEGIN TRANSACTION
BEGIN TRY
	UPDATE Camion
	SET Disponibilidad = 1
	WHERE Id = 1
	
	COMMIT TRANSACTION;
END TRY 
BEGIN CATCH 
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	PRINT 'Error Number: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
    PRINT 'Error Severity: ' + CAST(ERROR_SEVERITY() AS VARCHAR(10));
    PRINT 'Error State: ' + CAST(ERROR_STATE() AS VARCHAR(10));
    PRINT 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(10));
    PRINT 'Error Message: ' + ERROR_MESSAGE();
	--THROW;
END CATCH;
GO

-- UPDATE CHOFER
BEGIN TRANSACTION
BEGIN TRY
	UPDATE Chofer
	SET Disponibilidad = 1
	WHERE Id = 1
	
	COMMIT TRANSACTION;
END TRY 
BEGIN CATCH 
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	PRINT 'Error Number: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
    PRINT 'Error Severity: ' + CAST(ERROR_SEVERITY() AS VARCHAR(10));
    PRINT 'Error State: ' + CAST(ERROR_STATE() AS VARCHAR(10));
    PRINT 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(10));
    PRINT 'Error Message: ' + ERROR_MESSAGE();
	--THROW;
END CATCH;
GO

-- UPDATE CHOFER
BEGIN TRANSACTION
BEGIN TRY
	UPDATE Ruta
	SET FechaLlegada = '2026-03-22 08:30:00',
		FechaSalida = '2026-03-22 11:30:00'
	WHERE Id = 2
	
	COMMIT TRANSACTION;
END TRY 
BEGIN CATCH 
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION;

	PRINT 'Error Number: ' + CAST(ERROR_NUMBER() AS VARCHAR(10));
    PRINT 'Error Severity: ' + CAST(ERROR_SEVERITY() AS VARCHAR(10));
    PRINT 'Error State: ' + CAST(ERROR_STATE() AS VARCHAR(10));
    PRINT 'Error Line: ' + CAST(ERROR_LINE() AS VARCHAR(10));
    PRINT 'Error Message: ' + ERROR_MESSAGE();
	--THROW;
END CATCH;
GO
